CREATE TABLE TEST1(NAME VARCHAR(20) PRIMARY KEY,CORD SDO_GEOMETRY);

CREATE TABLE ANNOUNCEMENTSYSTEMS(BID VARCHAR(20) PRIMARY KEY,LOC SDO_GEOMETRY,RAD NUMBER);

CREATE TABLE BUILDINGS1(BID VARCHAR(80),BNAME VARCHAR(80),NOCORD NUMBER,SHAPE SDO_GEOMETRY);


INSERT INTO USER_SDO_GEOM_METADATA VALUES('TEST1','CORD',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,20,0.005),SDO_DIM_ELEMENT('Y',0,20,0.005)),NULL);

INSERT INTO USER_SDO_GEOM_METADATA VALUES('BUILDINGS1','SHAPE',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,20,0.005),SDO_DIM_ELEMENT('Y',0,20,0.005)),NULL);

INSERT INTO USER_SDO_GEOM_METADATA VALUES('ANNOUNCEMENTSYSTEMS','LOC',SDO_DIM_ARRAY(SDO_DIM_ELEMENT('X',0,20,0.005),SDO_DIM_ELEMENT('Y',0,20,0.005)),NULL);


CREATE INDEX STUD_IDX ON TEST1(CORD) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX BUILDING_IDX ON BUILDINGS1(SHAPE) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX AS_IDX ON ANNOUNCEMENTSYSTEMS(LOC) INDEXTYPE IS MDSYS.SPATIAL_INDEX;